# Configuration file for Google Cloud Build CI

steps:
- name: "rust"
  args: ["cargo", "doc"]
- name: "gcr.io/cloud-builders/gsutil"
  args: ["-m", "cp", "-r", "target/doc", "gs://sffc-chromium-ci-test-bucket/pr/$_PR_NUMBER/$BUILD_ID"]
