# Configuration file for Google Cloud Build CI

steps:
- name: "rust"
  args: ["cargo", "doc"]
artifacts:
  objects:
    location: "gs://sffc-chromium-ci-test-bucket/pr/$_PR_NUMBER/doc"
    paths:
    - target/doc
